//Chickent Products
const productChicken = [{
	id: 0,
	alt: "Buffalo Wings",
	name: "Buffalo Wings (6 pcs)", 
	price: 80,
	instock: 20,
	description: "Fried chicken coated in homemade buffalo sauce made with paprika and hot sauce.",
	imgSrc: "Images/Chicken/Buffalo-Wings.jpg",
},
{
	id: 1,
	alt: "Sweet Chili Wings",
	name: "Sweet Chili Wings (6 pcs)", 
	price: 80,
	instock: 20,
	description: "Wings coated with sweet ketchup mixed with hot sauce.",
	imgSrc: "Images/Chicken/Sweet-Chili-Wings.png",
},
{
	id: 2,
	alt: "Ultimate Spicy Chicken",
	name: "Ultimate Spicy Chicken (300-320g)", 
	price: 80,
	instock: 20,
	description: "Fried chicken seasoned with spices that set your mouth on fire",
	imgSrc: "Images/Chicken/Ultimate-Spicy-Chicken.png",
},
{
	id: 3,
	alt: "Salted Egg Wings",
	name: "Salted Egg Wings (6 pcs)", 
	price: 80,
	instock: 20,
	description: "Fried chicken wings cooked in mashed salted egg yolk sauce.",
	imgSrc: "Images/Chicken/Salted-Egg-Wings.jpg",
},
{
	id: 4,
	alt: "Salted Egg Chicken",
	name: "Salted Egg Chicken (300-320g)", 
	price: 80,
	instock: 20,
	description: "Fried chicken cooked in mashed salted egg yolk sauce.",
	imgSrc: "Images/Chicken/Salted-Egg-Chicken.png",
},
{
	id: 5,
	alt: "Simply Spicy Wings",
	name: "Simply Spicy Wings (6 pcs)", 
	price: 80,
	instock: 20,
	description: "Simple mildly spicy chicken",
	imgSrc: "Images/Chicken/Simply-Spicy-Chicken.png",
},
{
	id: 6,
	alt: "Garlic Parmesan Wings",
	name: "Garlic Parmesan Wings (6 pcs)", 
	price: 80,
	instock: 20,
	description: "Chicken wings with garlic powder and parmesan cheese",
	imgSrc: "Images/Chicken/Garlic-Parmesan-Wings.png",
},
{
	id: 7,
	alt: "Cheesy Chicken",
	name: "Cheesy Chicken (300-320g)", 
	price: 80,
	instock: 20,
	description: "Golden fried chicken topped with creamy cheese sauce.",
	imgSrc: "Images/Chicken/Cheesy-Chicken.png",
},
{
	id: 8,
	alt: "Butterd Chicken",
	name: "Butterd Chicken (300-320g)", 
	price: 80,
	instock: 20,
	description: "Golden fried chicken seasoned with spices and drenched in butter",
	imgSrc: "Images/Chicken/Buttered-Chicken.png",
},
{
	id: 9,
	alt: "Chili Garlic Chicken",
	name: "Chili Garlic Chicken (300-320g)", 
	price: 80,
	instock: 20,
	description: "Golden fried chicken drenched in chili garlic sauce with minced red and green peppers.",
	imgSrc: "Images/Chicken/Chili-Garlic-Chicken.jpg",
}];


//Pansit Products
const productFuncit = [{
	id: 10,
	alt: "Pancit Bihon",
	name: "Pancit Bihon 8-10", 
	price: 350,
	instock: 20,
	description: "Pancit that uses thin noodles mixed with vegetables and squid balls.",
	imgSrc: "Images/Funcit/Pancit-Bihon.jpg",
},
{
	id: 11,
	alt: "Pancit Canton",
	name: "Pancit Canton 8-10", 
	price: 350,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Canton.png",
},
{
	id: 12,
	alt: "Pancit Chami",
	name: "Pancit Chami 8-10", 
	price: 350,
	instock: 20,
	description: "Thick noodles mixed with vegetables and shrimp.",
	imgSrc: "Images/Funcit/Pancit-Chami.png",
},
{
	id: 13,
	alt: "Pancit Bihon",
	name: "Pancit Bihon 12-14", 
	price: 450,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Bihon.jpg",
},
{
	id: 14,
	alt: "Pancit Canton",
	name: "Pancit Canton 12-14", 
	price: 450,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Canton.png",
},
{
	id: 15,
	alt: "Pancit Chami",
	name: "Pancit Chami 12-14", 
	price: 450,
	instock: 20,
	description: "Thick noodles mixed with vegetables and shrimp.",
	imgSrc: "Images/Funcit/Pancit-Chami.png",
},
{
	id: 16,
	alt: "Pancit Bihon",
	name: "Pancit Bihon 16-18", 
	price: 550,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Bihon.jpg",
},
{
	id: 17,
	alt: "Pancit Canton",
	name: "Pancit Canton 16-18", 
	price: 550,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Canton.png",
},
{
	id: 18,
	alt: "Pancit Chami",
	name: "Pancit Chami 16-18", 
	price: 450,
	instock: 20,
	description: "Thick noodles mixed with vegetables and shrimp.",
	imgSrc: "Images/Funcit/Pancit-Chami.png",
},
{
	id: 19,
	alt: "Pancit Bihon",
	name: "Pancit Bihon 20-24", 
	price: 850,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Bihon.jpg",
},
{
	id: 20,
	alt: "Pancit Canton",
	name: "Pancit Canton 20-24", 
	price: 850,
	instock: 20,
	description: "Thick noodles mixed with vegetables and pieces of pork.",
	imgSrc: "Images/Funcit/Pancit-Canton.png",
},
{
	id: 21,
	alt: "Pancit Chami",
	name: "Pancit Chami 20-24", 
	price: 850,
	instock: 20,
	description: "Thick noodles mixed with vegetables and shrimp.",
	imgSrc: "Images/Funcit/Pancit-Chami.png",
},];


//Bangus Products
const productBangus = [{
	id: 22,
	alt: "Garlic Pepper Bangus",
	name: "Garlic Pepper Bangus 250g", 
	price: 99,
	instock: 20,
	description: "Boneless bangus topped with minced fried garlic and slices of red and green pepper.",
	imgSrc: "Images/Bangus/Garlic-Pepper-Bangus.jpg",
},
{
	id: 23,
	alt: "Cheesy Bangus",
	name: "Cheesy Bangus 250g", 
	price: 99,
	instock: 20,
	description: "Boneless bangus topped with shredded cheese.",
	imgSrc: "Images/Bangus/Cheesy-Bangus.png",
},
{
	id: 24,
	alt: "Steak Bangus",
	name: "Steak Bangus 250g", 
	price: 99,
	instock: 20,
	description: "Boneless bangus cooked like bistek with rings of onions.",
	imgSrc: "Images/Bangus/Steak-Bangus.png",
},
{
	id: 25,
	alt: "Garlic Parmesan Bangus",
	name: "Garlic Parmesan Bangus 250g", 
	price: 99,
	instock: 20,
	description: "Boneless bangus with garlic powder and parmesan cheese",
	imgSrc: "Images/Bangus/Garlic-Parmesan-Bangus.png",
}];


//Others Products
const productOthers = [{
	id: 26,
	alt: "Lumpiang Shanghai",
	name: "Lumpiang Shanghai", 
	price: 99,
	instock: 20,
	description: "Filipino egg roll filled with ground pork.",
	imgSrc: "Images/Others/Shanghai.jpg",
},
{
	id: 27,
	alt: "Fried Siomai",
	name: "Fried Siomai", 
	price: 99,
	instock: 20,
	description: "Deep fried pork dumplings.",
	imgSrc: "Images/Others/Siomai.jpg",
},
{
	id: 28,
	alt: "Crispy Chicken Sisig",
	name: "Crispy Chicken Sisig", 
	price: 99,
	instock: 20,
	description: "Chicken sisig with chili peppers and mayonnaise.",
	imgSrc: "Images/Others/Crispy-Chicken-Sisig.jpg",
},
{
	id: 29,
	alt: "Baked Macaroni",
	name: "Baked Macaroni", 
	price: 40 ,
	instock: 20,
	description: "Elbow shaped pasta, with spaghetti sauce and cheese.",
	imgSrc: "Images/Others/Baked-Macaroni.png",
},
{
	id: 30,
	alt: "Hungarian Sausage",
	name: "Hungarian Sausage", 
	price: 80,
	instock: 20,
	description: "Fried slightly spicy sausages with ketchup and mayonnaise.",
	imgSrc: "Images/Others/Hungarian-Sausage.jpg",
}];